{{- if and .Values.auth.secret (lt (len .Values.auth.secret) 32) }}
{{- fail "auth.secret must contain at least 32 characters" }}
{{- end }}
{{- if .Values.mongodb.uri }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litemcp.mongodbSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "litemcp.labels" . | nindent 4 }}
  {{- with .Values.mongodb.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.mongodb.key | quote }}: {{ .Values.mongodb.uri | quote }}
---
{{- end }}
{{- if .Values.auth.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litemcp.authSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "litemcp.labels" . | nindent 4 }}
  {{- with .Values.auth.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.auth.key | quote }}: {{ .Values.auth.secret | quote }}
{{- end }}
